import ClientProtBase from '#/network/game/client/codec/ClientProtBase.js';

export default class ClientProt244 extends ClientProtBase {
    static all: ClientProt244[] = [];
    static byId: ClientProt244[] = [];

    static readonly NO_TIMEOUT = new ClientProt244(6, 40, 0); // NXT naming

    static readonly IDLE_TIMER = new ClientProt244(30, 202, 0);
    static readonly EVENT_MOUSE_CLICK = new ClientProt244(31, 19, 4); // NXT naming
    static readonly EVENT_MOUSE_MOVE = new ClientProt244(32, 171, -1); // NXT naming
    static readonly EVENT_APPLET_FOCUS = new ClientProt244(33, 187, 1); // NXT naming
    static readonly EVENT_CAMERA_POSITION = new ClientProt244(35, 140, 4); // NXT naming
    static readonly EVENT_HAS_WINDOW = new ClientProt244(36, 78, 4);
    static readonly EVENT_SYNTH_ERROR = new ClientProt244(37, 80, 2);

    // autogenerated as part of obfuscation process
    static readonly ANTICHEAT_OPLOGIC1 = new ClientProt244(60, 95, 4);
    static readonly ANTICHEAT_OPLOGIC2 = new ClientProt244(61, 165, 1);
    static readonly ANTICHEAT_OPLOGIC3 = new ClientProt244(62, 157, 4);
    static readonly ANTICHEAT_OPLOGIC4 = new ClientProt244(63, 222, 3);
    static readonly ANTICHEAT_OPLOGIC5 = new ClientProt244(64, 126, 1);

    // autogenerated as part of obfuscation process
    static readonly ANTICHEAT_CYCLELOGIC1 = new ClientProt244(70, 244, -1);
    static readonly ANTICHEAT_CYCLELOGIC2 = new ClientProt244(71, 168, 0);
    static readonly ANTICHEAT_CYCLELOGIC3 = new ClientProt244(72, 197, 4);
    static readonly ANTICHEAT_CYCLELOGIC4 = new ClientProt244(73, 173, 3);
    static readonly ANTICHEAT_CYCLELOGIC5 = new ClientProt244(74, 248, 0);
    static readonly ANTICHEAT_CYCLELOGIC6 = new ClientProt244(75, 22, 2);

    static readonly OPOBJ1 = new ClientProt244(80, 77, 6); // NXT naming
    static readonly OPOBJ2 = new ClientProt244(81, 100, 6); // NXT naming
    static readonly OPOBJ3 = new ClientProt244(82, 71, 6); // NXT naming
    static readonly OPOBJ4 = new ClientProt244(83, 54, 6); // NXT naming
    static readonly OPOBJ5 = new ClientProt244(84, 230, 6); // NXT naming
    static readonly OPOBJT = new ClientProt244(88, 83, 8); // NXT naming
    static readonly OPOBJU = new ClientProt244(89, 211, 12); // NXT naming

    static readonly OPNPC1 = new ClientProt244(100, 112, 2); // NXT naming
    static readonly OPNPC2 = new ClientProt244(101, 67, 2); // NXT naming
    static readonly OPNPC3 = new ClientProt244(102, 13, 2); // NXT naming
    static readonly OPNPC4 = new ClientProt244(103, 42, 2); // NXT naming
    static readonly OPNPC5 = new ClientProt244(104, 8, 2); // NXT naming
    static readonly OPNPCT = new ClientProt244(108, 104, 4); // NXT naming
    static readonly OPNPCU = new ClientProt244(109, 57, 8); // NXT naming

    static readonly OPLOC1 = new ClientProt244(120, 181, 6); // NXT naming
    static readonly OPLOC2 = new ClientProt244(121, 241, 6); // NXT naming
    static readonly OPLOC3 = new ClientProt244(122, 50, 6); // NXT naming
    static readonly OPLOC4 = new ClientProt244(123, 136, 6); // NXT naming
    static readonly OPLOC5 = new ClientProt244(124, 55, 6); // NXT naming
    static readonly OPLOCT = new ClientProt244(128, 210, 8); // NXT naming
    static readonly OPLOCU = new ClientProt244(129, 152, 12); // NXT naming

    static readonly OPPLAYER1 = new ClientProt244(140, 245, 2); // NXT naming
    static readonly OPPLAYER2 = new ClientProt244(141, 233, 2); // NXT naming
    static readonly OPPLAYER3 = new ClientProt244(142, 194, 2); // NXT naming
    static readonly OPPLAYER4 = new ClientProt244(143, 116, 2); // NXT naming
    static readonly OPPLAYER5 = new ClientProt244(144, 45, 2); // NXT naming
    static readonly OPPLAYERT = new ClientProt244(148, 31, 4); // NXT naming
    static readonly OPPLAYERU = new ClientProt244(149, 143, 8); // NXT naming

    static readonly OPHELD1 = new ClientProt244(160, 203, 6); // name based on runescript trigger
    static readonly OPHELD2 = new ClientProt244(161, 24, 6); // name based on runescript trigger
    static readonly OPHELD3 = new ClientProt244(162, 161, 6); // name based on runescript trigger
    static readonly OPHELD4 = new ClientProt244(163, 228, 6); // name based on runescript trigger
    static readonly OPHELD5 = new ClientProt244(164, 4, 6); // name based on runescript trigger
    static readonly OPHELDT = new ClientProt244(168, 36, 8); // name based on runescript trigger
    static readonly OPHELDU = new ClientProt244(169, 1, 12); // name based on runescript trigger

    static readonly INV_BUTTON1 = new ClientProt244(190, 3, 6); // NXT has "IF_BUTTON1" but for our interface system, this makes more sense
    static readonly INV_BUTTON2 = new ClientProt244(191, 177, 6); // NXT has "IF_BUTTON2" but for our interface system, this makes more sense
    static readonly INV_BUTTON3 = new ClientProt244(192, 91, 6); // NXT has "IF_BUTTON3" but for our interface system, this makes more sense
    static readonly INV_BUTTON4 = new ClientProt244(193, 231, 6); // NXT has "IF_BUTTON4" but for our interface system, this makes more sense
    static readonly INV_BUTTON5 = new ClientProt244(194, 158, 6); // NXT has "IF_BUTTON5" but for our interface system, this makes more sense

    static readonly IF_BUTTON = new ClientProt244(200, 79, 2); // NXT naming
    static readonly RESUME_PAUSEBUTTON = new ClientProt244(201, 226, 2); // NXT naming
    static readonly CLOSE_MODAL = new ClientProt244(202, 110, 0); // NXT naming
    static readonly RESUME_P_COUNTDIALOG = new ClientProt244(203, 75, 4); // NXT naming
    static readonly TUTORIAL_CLICKSIDE = new ClientProt244(204, 119, 1); // no original name
    static readonly RESUME_P_NAMEDIALOG = new ClientProt244(205, 206, 8); // NXT naming

    static readonly MAP_BUILD_COMPLETE = new ClientProt244(241, 6, 0); // NXT naming
    static readonly MOVE_OPCLICK = new ClientProt244(242, 247, -1); // (comes with OP packets, name based on other MOVE packets)
    static readonly REPORT_ABUSE = new ClientProt244(243, 184, 10);
    static readonly MOVE_MINIMAPCLICK = new ClientProt244(244, 213, -1); // NXT naming
    static readonly INV_BUTTOND = new ClientProt244(245, 123, 7); // NXT has "IF_BUTTOND" but for our interface system, this makes more sense
    static readonly IGNORELIST_DEL = new ClientProt244(246, 160, 8); // NXT naming
    static readonly IGNORELIST_ADD = new ClientProt244(247, 217, 8); // NXT naming
    static readonly IF_PLAYERDESIGN = new ClientProt244(248, 163, 13);
    static readonly CHAT_SETMODE = new ClientProt244(249, 176, 3); // NXT naming
    static readonly MESSAGE_PRIVATE = new ClientProt244(250, 227, -1); // NXT naming
    static readonly FRIENDLIST_DEL = new ClientProt244(251, 141, 8); // NXT naming
    static readonly FRIENDLIST_ADD = new ClientProt244(252, 120, 8); // NXT naming
    static readonly CLIENT_CHEAT = new ClientProt244(253, 56, -1); // NXT naming
    static readonly MESSAGE_PUBLIC = new ClientProt244(254, 49, -1); // NXT naming
    static readonly MOVE_GAMECLICK = new ClientProt244(255, 28, -1); // NXT naming

    // in these old revisions we can actually get the packet index from a leftover array in the client source
    constructor(
        readonly index: number,
        readonly id: number,
        readonly length: number
    ) {
        super(index, id, length);

        ClientProt244.all[index] = this;
        ClientProt244.byId[id] = this;
    }
}
