export default class ClientGameProt {
    static all: ClientGameProt[] = [];
    static byId: ClientGameProt[] = [];

    static readonly NO_TIMEOUT = new ClientGameProt(6, 9000, 0); // NXT naming

    static readonly IDLE_TIMER = new ClientGameProt(30, 9002, 0);
    static readonly EVENT_MOUSE_CLICK = new ClientGameProt(31, 9003, 4); // NXT naming
    static readonly EVENT_MOUSE_MOVE = new ClientGameProt(32, 9004, -1); // NXT naming
    static readonly EVENT_APPLET_FOCUS = new ClientGameProt(33, 9005, 1); // NXT naming
    static readonly EVENT_CAMERA_POSITION = new ClientGameProt(35, 9006, 4); // NXT naming
    static readonly EVENT_HAS_WINDOW = new ClientGameProt(36, 9007, 4);
    static readonly EVENT_SYNTH_ERROR = new ClientGameProt(37, 9008, 2);

    // autogenerated as part of obfuscation process
    static readonly ANTICHEAT_OPLOGIC1 = new ClientGameProt(60, 9009, 4);
    static readonly ANTICHEAT_OPLOGIC2 = new ClientGameProt(61, 9010, 1);
    static readonly ANTICHEAT_OPLOGIC3 = new ClientGameProt(62, 9011, 4);
    static readonly ANTICHEAT_OPLOGIC4 = new ClientGameProt(63, 9012, 3);
    static readonly ANTICHEAT_OPLOGIC5 = new ClientGameProt(64, 9013, 1);

    // autogenerated as part of obfuscation process
    static readonly ANTICHEAT_CYCLELOGIC1 = new ClientGameProt(70, 9014, -1);
    static readonly ANTICHEAT_CYCLELOGIC2 = new ClientGameProt(71, 9015, 0);
    static readonly ANTICHEAT_CYCLELOGIC3 = new ClientGameProt(72, 9016, 4);
    static readonly ANTICHEAT_CYCLELOGIC4 = new ClientGameProt(73, 9017, 3);
    static readonly ANTICHEAT_CYCLELOGIC5 = new ClientGameProt(74, 9018, 0);
    static readonly ANTICHEAT_CYCLELOGIC6 = new ClientGameProt(75, 9019, 2);

    static readonly OPOBJ1 = new ClientGameProt(80, 9020, 6); // NXT naming
    static readonly OPOBJ2 = new ClientGameProt(81, 9021, 6); // NXT naming
    static readonly OPOBJ3 = new ClientGameProt(82, 9022, 6); // NXT naming
    static readonly OPOBJ4 = new ClientGameProt(83, 9023, 6); // NXT naming
    static readonly OPOBJ5 = new ClientGameProt(84, 9024, 6); // NXT naming
    static readonly OPOBJT = new ClientGameProt(88, 9025, 8); // NXT naming
    static readonly OPOBJU = new ClientGameProt(89, 9026, 12); // NXT naming

    static readonly OPNPC1 = new ClientGameProt(100, 9027, 2); // NXT naming
    static readonly OPNPC2 = new ClientGameProt(101, 9028, 2); // NXT naming
    static readonly OPNPC3 = new ClientGameProt(102, 9029, 2); // NXT naming
    static readonly OPNPC4 = new ClientGameProt(103, 9030, 2); // NXT naming
    static readonly OPNPC5 = new ClientGameProt(104, 9031, 2); // NXT naming
    static readonly OPNPCT = new ClientGameProt(108, 9032, 4); // NXT naming
    static readonly OPNPCU = new ClientGameProt(109, 9033, 8); // NXT naming

    static readonly OPLOC1 = new ClientGameProt(120, 9034, 6); // NXT naming
    static readonly OPLOC2 = new ClientGameProt(121, 9035, 6); // NXT naming
    static readonly OPLOC3 = new ClientGameProt(122, 9036, 6); // NXT naming
    static readonly OPLOC4 = new ClientGameProt(123, 9037, 6); // NXT naming
    static readonly OPLOC5 = new ClientGameProt(124, 9038, 6); // NXT naming
    static readonly OPLOCT = new ClientGameProt(128, 9039, 8); // NXT naming
    static readonly OPLOCU = new ClientGameProt(129, 9040, 12); // NXT naming

    static readonly OPPLAYER1 = new ClientGameProt(140, 9041, 2); // NXT naming
    static readonly OPPLAYER2 = new ClientGameProt(141, 9042, 2); // NXT naming
    static readonly OPPLAYER3 = new ClientGameProt(142, 9043, 2); // NXT naming
    static readonly OPPLAYER4 = new ClientGameProt(143, 9044, 2); // NXT naming
    static readonly OPPLAYER5 = new ClientGameProt(144, 9045, 2); // NXT naming
    static readonly OPPLAYERT = new ClientGameProt(148, 9046, 4); // NXT naming
    static readonly OPPLAYERU = new ClientGameProt(149, 9047, 8); // NXT naming

    static readonly OPHELD1 = new ClientGameProt(160, 9048, 6); // name based on runescript trigger
    static readonly OPHELD2 = new ClientGameProt(161, 9049, 6); // name based on runescript trigger
    static readonly OPHELD3 = new ClientGameProt(162, 9050, 6); // name based on runescript trigger
    static readonly OPHELD4 = new ClientGameProt(163, 9051, 6); // name based on runescript trigger
    static readonly OPHELD5 = new ClientGameProt(164, 9052, 6); // name based on runescript trigger
    static readonly OPHELDT = new ClientGameProt(168, 9053, 8); // name based on runescript trigger
    static readonly OPHELDU = new ClientGameProt(169, 9054, 12); // name based on runescript trigger

    static readonly INV_BUTTON1 = new ClientGameProt(190, 9055, 6); // NXT has "IF_BUTTON1" but for our interface system, this makes more sense
    static readonly INV_BUTTON2 = new ClientGameProt(191, 9056, 6); // NXT has "IF_BUTTON2" but for our interface system, this makes more sense
    static readonly INV_BUTTON3 = new ClientGameProt(192, 9057, 6); // NXT has "IF_BUTTON3" but for our interface system, this makes more sense
    static readonly INV_BUTTON4 = new ClientGameProt(193, 9058, 6); // NXT has "IF_BUTTON4" but for our interface system, this makes more sense
    static readonly INV_BUTTON5 = new ClientGameProt(194, 9059, 6); // NXT has "IF_BUTTON5" but for our interface system, this makes more sense

    static readonly IF_BUTTON = new ClientGameProt(200, 79, 9060); // NXT naming
    static readonly RESUME_PAUSEBUTTON = new ClientGameProt(201, 9061, 2); // NXT naming
    static readonly CLOSE_MODAL = new ClientGameProt(202, 9062, 0); // NXT naming
    static readonly RESUME_P_COUNTDIALOG = new ClientGameProt(203, 9063, 4); // NXT naming
    static readonly TUTORIAL_CLICKSIDE = new ClientGameProt(204, 9064, 1); // no original name
    static readonly RESUME_P_NAMEDIALOG = new ClientGameProt(205, 9065, 8); // NXT naming

    static readonly MAP_BUILD_COMPLETE = new ClientGameProt(241, 9066, 0); // NXT naming
    static readonly MOVE_OPCLICK = new ClientGameProt(242, 254, -1); // (comes with OP packets, name based on other MOVE packets)
    static readonly REPORT_ABUSE = new ClientGameProt(243, 9068, 10);
    static readonly MOVE_MINIMAPCLICK = new ClientGameProt(244, 39, -1); // NXT naming
    static readonly INV_BUTTOND = new ClientGameProt(245, 9070, 7); // NXT has "IF_BUTTOND" but for our interface system, this makes more sense
    static readonly IGNORELIST_DEL = new ClientGameProt(246, 9071, 8); // NXT naming
    static readonly IGNORELIST_ADD = new ClientGameProt(247, 9072, 8); // NXT naming
    static readonly IF_PLAYERDESIGN = new ClientGameProt(248, 9073, 13);
    static readonly CHAT_SETMODE = new ClientGameProt(249, 9074, 3); // NXT naming
    static readonly MESSAGE_PRIVATE = new ClientGameProt(250, 9075, -1); // NXT naming
    static readonly FRIENDLIST_DEL = new ClientGameProt(251, 9076, 8); // NXT naming
    static readonly FRIENDLIST_ADD = new ClientGameProt(252, 9077, 8); // NXT naming
    static readonly CLIENT_CHEAT = new ClientGameProt(253, 44, -1); // NXT naming
    static readonly MESSAGE_PUBLIC = new ClientGameProt(254, 9079, -1); // NXT naming
    static readonly MOVE_GAMECLICK = new ClientGameProt(255, 215, -1); // NXT naming

    // in these old revisions we can actually get the packet index from a leftover array in the client source
    constructor(
        readonly index: number,
        readonly id: number,
        readonly length: number
    ) {
        ClientGameProt.all[index] = this;
        ClientGameProt.byId[id] = this;
    }
}
